version: "2"
services:
  ember:
    image: fastboot
    volumes:
      - /home/cecemel/git/fabbrikka-frontend/dist:/dist
  identifier:
    image: semtech/mu-identifier:1.0.0
    links:
      - dispatcher:dispatcher
    ports:
      - "6970:80"
  dispatcher:
    image: semtech/mu-dispatcher:1.0.1
    links:
      - resource:resource
      - ember:ember
    volumes:
      - ./config/dispatcher:/config
  db:
    image: tenforce/virtuoso:1.0.0-virtuoso7.2.4
    environment:
      SPARQL_UPDATE: "true"
      DEFAULT_GRAPH: "http://mu.semte.ch/application"
    ports:
      - "8890:8890"
    volumes:
      - ./data/db:/data
  resource:
    image: semtech/mu-cl-resources:1.12.1
    links:
      - db:database
    volumes:
      - ./config/resources:/config
  file-service:
    image: semtech/mu-file-service
    links:
      - db:database
    volumes:
      - ./data/files:/data
    ports:
      - "6971:80"
    environment:
      - SECRET_KEY_BASE=test
